version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: nani
      MONGO_INITDB_ROOT_PASSWORD: nani
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=mern_app_db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

volumes:
  mongodb_data:
